openapi: 3.0.3
info:
    title: 'VNJobs API Documentaion'
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths:
    /api/v1/auth/login:
        post:
            summary: Login.
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - 'Auth endpoints'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: String
                                    description: ''
                                    example: earum
                                password:
                                    type: String
                                    description: ''
                                    example: et
                            required:
                                - email
                                - password
            security: []
